# Based on:
# https://gist.github.com/dan-blanchard/7045057
# https://github.com/Jorge-C/ordination/blob/master/.travis.yml
# https://github.com/soft-matter/trackpy/blob/master/.travis.yml
# http://conda.pydata.org/docs/travis.html

# See also: https://github.com/travis-ci/travis-ci/issues/2650

language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

# Download and set up anaconda
before_install:
  - npm install -g grunt-cli
  - npm install

# Install packages
install:
  - pip install -r requirements.txt

# Run test(s)
script:
  - py.test
  - grunt travis -v
  - flake8 --exclude docs/conf.py --max-line-length=100
