# Based on:
# https://gist.github.com/dan-blanchard/7045057
# https://github.com/Jorge-C/ordination/blob/master/.travis.yml
# https://github.com/soft-matter/trackpy/blob/master/.travis.yml
# http://conda.pydata.org/docs/travis.html

# See also: https://github.com/travis-ci/travis-ci/issues/2650

language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - npm install

# Install packages
install:
  - pip install -r requirements.txt
  - pre-commit install

# Run test(s)
script:
  - pre-commit run --all-files
  - py.test
