name: scout
channels:
  - defaults
dependencies:
  - numpy
  - pandas
  - plotly
  - dash
  - pip
  - pip:
    - coverage
    - tox
    - dash_bootstrap_components
    - tabulate
    - numpy_financial
    - pyam-iamc